-- require('plugins/install')
require('plugins/lsp')
require('plugins/lualine')
require('plugins/colorscheme')
require('plugins/treesitter')
require('plugins/formatter')
require('plugins/fzf')
require('plugins/surround')
require('plugins/lir')
require('plugins/flash')
